language: generic
sudo: required
services:
  - docker

before_install:
  - docker run -t vishwanathg7145/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vishwanathg7145/docker-react npm start test